CREATE LOGIN Manager1 WITH PASSWORD = 'Manager1Pass';
CREATE USER Manager1 FOR LOGIN Manager1;
ALTER ROLE Management ADD MEMBER Manager1;

CREATE LOGIN Staff1 WITH PASSWORD = 'Staff1Pass';
CREATE USER Staff1 FOR LOGIN Staff1;
ALTER ROLE Staff ADD MEMBER Staff1;